import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header/header'
import Dashboard from '../components/dashboard/dashboard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>IIVEDA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Header/>
     <Dashboard/>
    </div>
  )
}
